### ISSUE TITLE
Add star for Washington, D.C.

### ISSUE THREAD

**Issue by awunderground** [UrbanInstitute/urbnmapr#17]

**Comment by bchartoff** [comment]
Can this be a flag/option, with default set to no star? Some folks have used the star in the past, and for consistencies sake I'm fine keeping it on an as-needed basis, but also want to make sure we can produce state level choropleths w/ no star.

**Comment by awunderground** [comment]
Thanks for the feedback. Yep, that's the plan! The star is for a specific team that is interested in testing R for mapping.

**Comment by awunderground** [comment]
Added to urbnmapr ccdf map and label
