### ISSUE TITLE
Add sf = TRUE/FALSE to get_urbn_map

### ISSUE THREAD

**Issue by awunderground** [UrbanInstitute/urbnmapr#40]
[special features](https://github.com/r-spatial/sf) is one of the great geospatial innovations of the last few years. 

Adding a `sf = ` argument to `get_urbn_map()` will allow `library(urbnmapr)` to include `sf` but won't sacrifice the intuitive interface for building choropleths that appeals to newer R users. 

This function will convert data that is downloaded with `get_urbn_map()` to `sf` format. The argument should default to `FALSE`.

**Comment by sstrochak** [comment]
@awunderground the `ccdf` option of `get_urbn_map()` is created differently than the `states` dataframe. Do we need to implement `sf` for the CCDF map also? Not sure it is needed since that map has a pretty specific use case.

**Comment by awunderground** [comment]
Closed with P.R. #50
