### ISSUE TITLE
Add territories_states option

### ISSUE THREAD

**Issue by hrecht** [UrbanInstitute/urbnmapr#47]
Hey, thanks for this awesome package and especially for the territories_counties option.

When drawing state borders on top of that though, there doesn't appear to be a corresponding state layer that includes territories - unless I'm just not seeing it? That would be great to have as well.

**Comment by sstrochak** [comment]
@hrecht you are correct! we are working on that now.

**Comment by sstrochak** [comment]
@hrecht we added this, as well as `sf` options! 

closed with P.R. #50
