### ISSUE TITLE
Include discrete color scale in examples

### ISSUE THREAD

**Issue by bchartoff** [UrbanInstitute/urbnmapr#49]
While many maps definitely make sense with a continuous color scale, I'd love it if the documentation could include an example of a discrete scale (useful for categorical data, or for continuous data with extreme outliers that belong in a top or bottom bin, which would throw off a linearly continuous scale)

In my mind not a change to core package, just a further documentation example (using a [manual scale](https://ggplot2.tidyverse.org/reference/scale_manual.html) right?) but let me know if that seems off

**Comment by sstrochak** [comment]
@bchartoff this is a great idea, and a question I get a lot. I'm making some updates now and will incorporate this.

**Comment by sstrochak** [comment]
closed with P.R. #50
